framework:
  messenger:
    reset_on_message: true

    buses:
      messenger.bus.default:
        default_middleware: allow_no_handlers
        middleware:
          - Like\NotificationQueueBundle\Messenger\AuditMiddleware

    failure_transport: failed

    transports:
      async:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        serializer: Like\NotificationQueueBundle\Serializer\Messenger\MessageSerializer
        options:
          auto_setup: true
          queues:
            push:
              binding_keys:
                - push
          exchange:
            name: app.lms
            type: direct

      failed: "doctrine://default?queue_name=failed"

    routing:
      'Like\NotificationQueueBundle\Message\PushNotificationMessage': async

