parameters:
    messenger:
        push_notification: 'Like\NotificationQueueBundle\Message\PushNotificationMessage'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Like\NotificationQueueBundle\:
        resource: '../src/'

    Like\NotificationQueueBundle\Serializer\Messenger\MessageSerializer:
        class: Like\NotificationQueueBundle\Serializer\Messenger\MessageSerializer
        arguments:
            - '%messenger%'



