services:
  _defaults:
    autowire: true
    autoconfigure: true

  Like\NotificationQueueBundle\:
    resource: '../src/'

parameters:
  messenger.mapping:
    push_notification: 'Like\NotificationQueueBundle\Message\PushNotificationMessage'
